# Copyright 2026 FER, HPC Architecture and Application Research Center
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
#
# Licensed under the Solderpad Hardware License v 2.1 (the "License");
# you may not use this file except in compliance with the License, or,
# at your option, the Apache License version 2.0.
# You may obtain a copy of the License at https://solderpad.org/licenses/SHL-2.1/

# Based on https://github.com/IHP-GmbH/ihp-sg13cmos5l-librelane-template/blob/main/librelane/config.yaml

meta:
  version: 3
  flow: Chip
  substituting_steps:
    # Magic reports some overlaps which can be ignored
    Checker.IllegalOverlap: null
    # Disable magic DRC, not supported by the PDK
    Magic.DRC: null
    Checker.MagicDRC: null
    # Disable KLayout antenna check
    KLayout.Antenna: null
    Checker.KLayoutAntenna: null

DESIGN_NAME: chip_top
VERILOG_FILES:
- dir::../src/chip_top.sv

# TARGET_ASIC swaps hw/configurable_delay.sv from a passthrough to the hardened delay_line_D4_O1_6P000 macro
VERILOG_DEFINES: [FUNCTIONAL, TARGET_ASIC]

# Enable plugin for better SystemVerilog support
USE_SLANG: true
SLANG_ARGUMENTS: ['--keep-hierarchy', '-F', 'ref::$DESIGN_DIR/../sources.f']

# Keep part of the hierarchy for debugging and librelane-image target
# SYNTH_KEEP_HIERARCHY_INSTANCES: [
#     # '*friscv_chip_soc*/i_hyperbus',       # HyperBus
#     '*friscv_core_complex*/cpu_0',        # FRISC-V
#     '*friscv_id_stage*/regfile',          # Regfile
#     '*friscv_core_complex*/gen_mmu.mmu',  # MMU
#     '*vernii_soc*/dmi',                   # JTAG
#     '*vernii_soc*/dm',                    # DM
#     '*vernii_soc*/clint',                 # ACLINT
#     '*vernii_soc*/plic',                  # PLIC
#     '*vernii_soc*/gpio_a',                # GPIO A
#     '*vernii_soc*/qspi0',                 # QSPI0
#     '*vernii_soc*/uart0',                 # UART0
#     '*vernii_soc*/scb'                    # SCB
# ]

RUN_LINTER: false

ERROR_ON_SYNTH_CHECKS: false

# Slightly smaller file sizes
PRIMARY_GDSII_STREAMOUT_TOOL: klayout

# Specify the pad instances for the padring
PAD_SOUTH: [
    "hb_dq_pads\\[0\\].hb_dq_pad",       # S0  HB_DQ0
    "hb_dq_pads\\[1\\].hb_dq_pad",       # S1  HB_DQ1
    "hb_dq_pads\\[2\\].hb_dq_pad",       # S2  HB_DQ2
    "hb_dq_pads\\[3\\].hb_dq_pad",       # S3  HB_DQ3
    "iovss_pads\\[0\\].iovss_pad",       # S4  IOVSS
    "hb_dq_pads\\[4\\].hb_dq_pad",       # S5  HB_DQ4
    "hb_dq_pads\\[5\\].hb_dq_pad",       # S6  HB_DQ5
    "hb_dq_pads\\[6\\].hb_dq_pad",       # S7  HB_DQ6
    "hb_dq_pads\\[7\\].hb_dq_pad",       # S8  HB_DQ7
    hb_rwds_pad,                         # S9  HB_RWDS
    "iovdd_pads\\[0\\].iovdd_pad",       # S10 IOVDD
    hb_ck_pad,                           # S11 HB_CK
    "vdd_pads\\[0\\].vdd_pad",           # S12 VDD
    "hb_cs_pads\\[0\\].hb_cs_pad",       # S13 HB_CS0#
    "hb_cs_pads\\[1\\].hb_cs_pad",       # S14 HB_CS1#
    "vss_pads\\[0\\].vss_pad"            # S15 VSS
]

PAD_EAST: [
    hb_rst_pad,                          # E0  HB_RST#
    "gpio_a_pads\\[0\\].gpio_a_pad",     # E1  PA0
    "gpio_a_pads\\[1\\].gpio_a_pad",     # E2  PA1
    "gpio_a_pads\\[2\\].gpio_a_pad",     # E3  PA2
    "iovss_pads\\[1\\].iovss_pad",       # E4  IOVSS
    "iovdd_pads\\[1\\].iovdd_pad",       # E5  IOVDD
    "gpio_a_pads\\[3\\].gpio_a_pad",     # E6  PA3
    "gpio_a_pads\\[4\\].gpio_a_pad",     # E7  PA4
    "vss_pads\\[1\\].vss_pad",           # E8  VSS
    clk_out_pad,                         # E9  CLK_OUT
    "vdd_pads\\[1\\].vdd_pad",           # E10 VDD
    "gpio_a_pads\\[5\\].gpio_a_pad",     # E11 PA5
    "gpio_a_pads\\[6\\].gpio_a_pad",     # E12 PA6
    "gpio_a_pads\\[7\\].gpio_a_pad",     # E13 PA7
    "iovss_pads\\[2\\].iovss_pad",       # E14 IOVSS
    "iovdd_pads\\[2\\].iovdd_pad"        # E15 IOVDD
]

PAD_NORTH: [
    "vdd_pads\\[3\\].vdd_pad",           # N0  VDD
    "vss_pads\\[3\\].vss_pad",           # N1  VSS
    "gpio_a_pads\\[8\\].gpio_a_pad",     # N2  PA8
    "gpio_a_pads\\[9\\].gpio_a_pad",     # N3  PA9
    "qspi0_cs_pads\\[2\\].qspi0_cs_pad", # N4  QSPI0_CS2#
    "qspi0_cs_pads\\[1\\].qspi0_cs_pad", # N5  QSPI0_CS1#
    "qspi0_cs_pads\\[0\\].qspi0_cs_pad", # N6  QSPI0_CS0#
    "iovdd_pads\\[3\\].iovdd_pad",       # N7  IOVDD
    "iovss_pads\\[3\\].iovss_pad",       # N8  IOVSS
    qspi0_sck_pad,                       # N9  QSPI0_SCK
    "vdd_pads\\[2\\].vdd_pad",           # N10 VDD
    "vss_pads\\[2\\].vss_pad",           # N11 VSS
    "qspi0_io_pads\\[3\\].qspi0_io_pad", # N12 QSPI0_IO3
    "qspi0_io_pads\\[2\\].qspi0_io_pad", # N13 QSPI0_IO2
    "qspi0_io_pads\\[1\\].qspi0_io_pad", # N14 QSPI0_IO1
    "qspi0_io_pads\\[0\\].qspi0_io_pad"  # N15 QSPI0_IO0
]

PAD_WEST: [
    "iovdd_pads\\[4\\].iovdd_pad",       # W0  IOVDD
    clk_pad,                             # W1  CLK
    "iovss_pads\\[5\\].iovss_pad",       # W2  IOVSS
    rst_n_pad,                           # W3  RST#
    uart0_rx_pad,                        # W4  UART0_RX
    uart0_tx_pad,                        # W5  UART0_TX
    "iovss_pads\\[4\\].iovss_pad",       # W6  IOVSS
    jtag_tdo_pad,                        # W7  TDO
    jtag_tdi_pad,                        # W8  TDI
    jtag_tms_pad,                        # W9  TMS
    "vdd_pads\\[5\\].vdd_pad",           # W10 VDD
    jtag_tck_pad,                        # W11 TCK
    "vss_pads\\[5\\].vss_pad",           # W12 VSS
    jtag_trst_n_pad,                     # W13 TRST#
    "vss_pads\\[4\\].vss_pad",           # W14 VSS
    "vdd_pads\\[4\\].vdd_pad"            # W15 VDD
]

# SDC files
PNR_SDC_FILE: dir::chip_top.sdc
SIGNOFF_SDC_FILE: dir::chip_top.sdc
FALLBACK_SDC: dir::chip_top.sdc

# Power / ground nets
VDD_NETS:
- VDD
GND_NETS:
- VSS

# Clock
CLOCK_PORT: clk_PAD
CLOCK_NET: clk_pad/p2c

CLOCK_PERIOD: 13.5

SYNTH_STRATEGY: "DELAY 0"
SYNTH_ABC_BUFFERING: true
PL_TIMING_DRIVEN: true

# Floorplanning
FP_SIZING: absolute
DIE_AREA: [0, 0, 2100, 2100]
CORE_AREA: [336, 336, 1764, 1764]

FP_MACRO_HORIZONTAL_HALO: 5
FP_MACRO_VERTICAL_HALO: 5

# Keep signal routing off the SRAM macro power stripes
# Do not use GRT_MACRO_EXTENSION for this
ROUTING_OBSTRUCTIONS:
# gen_ways[0]  416.64 x 191.34 @ [336.00,  852.28]
- ["Metal4",    336.00,  852.28,  752.64, 1043.62]
- ["TopMetal1", 336.00,  852.28,  752.64, 1043.62]
# gen_ways[1]  416.64 x 191.34 @ [1347.36, 852.28]
- ["Metal4",   1347.36,  852.28, 1764.00, 1043.62]
- ["TopMetal1",1347.36,  852.28, 1764.00, 1043.62]
# gen_ways[2]  416.64 x 191.34 @ [336.00, 1054.28]
- ["Metal4",    336.00, 1054.28,  752.64, 1245.62]
- ["TopMetal1", 336.00, 1054.28,  752.64, 1245.62]
# gen_ways[3]  416.64 x 191.34 @ [1347.36, 1054.28]
- ["Metal4",   1347.36, 1054.28, 1764.00, 1245.62]
- ["TopMetal1",1347.36, 1054.28, 1764.00, 1245.62]
# gen_tag_sram 784.48 x  64.36 @ [657.76, 1697.12]
- ["Metal4",    657.76, 1697.12, 1442.24, 1761.48]
- ["TopMetal1", 657.76, 1697.12, 1442.24, 1761.48]

PL_TARGET_DENSITY_PCT: 85
GRT_ALLOW_CONGESTION: true

GRT_ADJUSTMENT: 0.22

SETUP_VIOLATION_CORNERS: ["*"]

GRT_DESIGN_REPAIR_MAX_CAP_PCT: 20
GRT_DESIGN_REPAIR_MAX_SLEW_PCT: 30

PL_RESIZER_HOLD_SLACK_MARGIN: 0.1
GRT_RESIZER_HOLD_SLACK_MARGIN: 0.1

TIME_DERATING_CONSTRAINT: 2

DESIGN_REPAIR_MAX_WIRE_LENGTH: 800
CTS_CLK_MAX_WIRE_LENGTH: 800
GRT_DESIGN_REPAIR_MAX_WIRE_LENGTH: 0
WIRE_LENGTH_THRESHOLD: 2500

MAX_TRANSITION_CONSTRAINT: 0.75

LAYERS_RC:
  "*":
    Metal1:    {res: 0.00084375,   cap: 0.000137568}
    Metal2:    {res: 0.000515,     cap: 0.000186040}
    Metal3:    {res: 0.000515,     cap: 0.000184000}
    Metal4:    {res: 0.000515,     cap: 0.000183576}
    TopMetal1: {res: 0.0000128049, cap: 0.000221699}

# Signoff waivers
# KLayout DRC
# ERROR_ON_KLAYOUT_DRC: false
# KLayout density
# TODO check if we can do this
# ERROR_ON_KLAYOUT_DENSITY: false
# Max capacitance
# TODO check if we can do this also
# MAX_CAP_VIOLATION_CORNERS: ["*"]

RUN_POST_GRT_DESIGN_REPAIR: true
RUN_POST_GRT_RESIZER_TIMING: true

CTS_APPLY_NDR: none

# PDN
PDN_CORE_RING: True

# Override bondpad name
PAD_BONDPAD_NAME: bondpad_70x70_5L

# Bondpad is not yet included in the PDK
EXTRA_GDS:
- dir::../ip/bondpad_70x70/gds/bondpad_70x70_5L.gds

EXTRA_LEFS:
- dir::../ip/bondpad_70x70/lef/bondpad_70x70_5L.lef

IGNORE_DISCONNECTED_MODULES:
- bondpad_70x70_5L

PDN_CORE_RING_VWIDTH: 5
PDN_CORE_RING_HWIDTH: 5
PDN_CORE_RING_VSPACING: 2
PDN_CORE_RING_HSPACING: 2

PDN_CORE_RING_CONNECT_TO_PADS: true
PDN_ENABLE_PINS: false

# Because we have multiple power pads for one power domain
MAGIC_EXT_UNIQUE: notopports

MACROS:
  RM_IHPSG13_1P_512x32_c2_bm_bist:
    gds:
      - pdk_dir::libs.ref/sg13cmos5l_sram/gds/RM_IHPSG13_1P_512x32_c2_bm_bist.gds
    lef:
      - pdk_dir::libs.ref/sg13cmos5l_sram/lef/RM_IHPSG13_1P_512x32_c2_bm_bist.lef
    vh:
      - pdk_dir::libs.ref/sg13cmos5l_sram/verilog/RM_IHPSG13_1P_512x32_c2_bm_bist.v
      - pdk_dir::libs.ref/sg13cmos5l_sram/verilog/RM_IHPSG13_1P_core_behavioral_bm_bist.v
    lib:
      "*_typ_1p20V_25C":
        - pdk_dir::libs.ref/sg13cmos5l_sram/lib/RM_IHPSG13_1P_512x32_c2_bm_bist_typ_1p20V_25C.lib
      "*_fast_1p32V_m40C":
        - pdk_dir::libs.ref/sg13cmos5l_sram/lib/RM_IHPSG13_1P_512x32_c2_bm_bist_fast_1p32V_m55C.lib
      "*_slow_1p08V_125C":
        - pdk_dir::libs.ref/sg13cmos5l_sram/lib/RM_IHPSG13_1P_512x32_c2_bm_bist_slow_1p08V_125C.lib
    instances:
      soc_inst.i_vernii_soc.friscv_mem_hub.ocm_llc.gen_ways[0].way_sram.gen_512x32.gen_cuts[0].i_cut:
        location: [336.0, 852.28]
        orientation: N
      soc_inst.i_vernii_soc.friscv_mem_hub.ocm_llc.gen_ways[1].way_sram.gen_512x32.gen_cuts[0].i_cut:
        location: [1347.36, 852.28]
        orientation: N
      soc_inst.i_vernii_soc.friscv_mem_hub.ocm_llc.gen_ways[2].way_sram.gen_512x32.gen_cuts[0].i_cut:
        location: [336.0, 1054.28]
        orientation: FS
      soc_inst.i_vernii_soc.friscv_mem_hub.ocm_llc.gen_ways[3].way_sram.gen_512x32.gen_cuts[0].i_cut:
        location: [1347.36, 1054.28]
        orientation: FS
  RM_IHPSG13_1P_64x64_c2_bm_bist:
    gds:
      - pdk_dir::libs.ref/sg13cmos5l_sram/gds/RM_IHPSG13_1P_64x64_c2_bm_bist.gds
    lef:
      - pdk_dir::libs.ref/sg13cmos5l_sram/lef/RM_IHPSG13_1P_64x64_c2_bm_bist.lef
    vh:
      - pdk_dir::libs.ref/sg13cmos5l_sram/verilog/RM_IHPSG13_1P_64x64_c2_bm_bist.v
      - pdk_dir::libs.ref/sg13cmos5l_sram/verilog/RM_IHPSG13_1P_core_behavioral_bm_bist.v
    lib:
      "*_typ_1p20V_25C":
        - pdk_dir::libs.ref/sg13cmos5l_sram/lib/RM_IHPSG13_1P_64x64_c2_bm_bist_typ_1p20V_25C.lib
      "*_fast_1p32V_m40C":
        - pdk_dir::libs.ref/sg13cmos5l_sram/lib/RM_IHPSG13_1P_64x64_c2_bm_bist_fast_1p32V_m55C.lib
      "*_slow_1p08V_125C":
        - pdk_dir::libs.ref/sg13cmos5l_sram/lib/RM_IHPSG13_1P_64x64_c2_bm_bist_slow_1p08V_125C.lib
    instances:
      soc_inst.i_vernii_soc.friscv_mem_hub.ocm_llc.gen_tag_sram.tag_sram.gen_64x64.i_cut:
        location: [657.76, 1697.12]
        orientation: N
  # HyperBus PHY delay line, 6 ns full scale at 0.375 ns/step
  # Ported from cheshire-ihp130-o to CMOS5L
  # Only tt corner characterized, all point at it, similar to Basilisk
  delay_line_D4_O1_6P000:
    gds:
      - dir::../src/mc_delay/views/delay_line_D4_O1_6P000.gds
    lef:
      - dir::../src/mc_delay/views/delay_line_D4_O1_6P000.abst.lef
    lib:
      "*_typ_1p20V_25C":
        - dir::../src/mc_delay/views/delay_line_D4_O1_6P000.lib
      "*_fast_1p32V_m40C":
        - dir::../src/mc_delay/views/delay_line_D4_O1_6P000.lib
      "*_slow_1p08V_125C":
        - dir::../src/mc_delay/views/delay_line_D4_O1_6P000.lib
    instances:
      # RWDS
      soc_inst.i_hyperbus.i_phy.genblk1.i_phy.i_trx.i_delay_rx_rwds_90.i_delay.i_delay_line:
        location: [1290.24, 366.66]
        orientation: N
      # CK
      soc_inst.i_hyperbus.genblk1.i_delay_tx_clk_90.i_delay.i_delay_line:
        location: [1392.0, 366.66]
        orientation: N

# This is an alternative method compared to
# specifying the power connections in the RTL
PDN_MACRO_CONNECTIONS:
- ".*gen_512x32.gen_cuts.*i_cut VDD VSS VDDARRAY! VSS!"
- ".*gen_512x32.gen_cuts.*i_cut VDD VSS VDD! VSS!"
- ".*gen_64x64.i_cut VDD VSS VDDARRAY! VSS!"
- ".*gen_64x64.i_cut VDD VSS VDD! VSS!"
- ".*i_delay_line VDD VSS VDD VSS"
