# Based on https://github.com/IHP-GmbH/ihp-sg13cmos5l-librelane-template/blob/main/librelane/config.yaml

meta:
  version: 3
  flow: Chip
  substituting_steps:
    # Magic reports some overlaps which can be ignored
    Checker.IllegalOverlap: null
    # Disable magic DRC
    Magic.DRC: null
    Checker.MagicDRC: null
    # Disable KLayout antenna check
    KLayout.Antenna: null
    Checker.KLayoutAntenna: null

DESIGN_NAME: friscv_soc_top
VERILOG_FILES:
- dir::../src/friscv_soc_top.sv

VERILOG_DEFINES: [FUNCTIONAL]

# Enable plugin for better SystemVerilog support
USE_SLANG: true
SLANG_ARGUMENTS: ['--keep-hierarchy', '-F', 'ref::$DESIGN_DIR/../sources.f']

RUN_LINTER: false

ERROR_ON_SYNTH_CHECKS: false

# Slightly smaller file sizes
PRIMARY_GDSII_STREAMOUT_TOOL: klayout

# Specify the pad instances for the padring
PAD_SOUTH: [
    "bidirs\\[13\\].bidir_pad",     #  1  PA13  HB_DQ0  / DBG_D0
    "bidirs\\[14\\].bidir_pad",     #  2  PA14  HB_DQ1  / DBG_D1
    "bidirs\\[15\\].bidir_pad",     #  3  PA15  HB_DQ2  / DBG_D2
    "bidirs\\[16\\].bidir_pad",     #  4  PA16  HB_DQ3  / DBG_D3
    "iovdd_pads\\[0\\].iovdd_pad",  #  5  IOVDD
    "bidirs\\[17\\].bidir_pad",     #  6  PA17  HB_DQ4  / DBG_D4
    "bidirs\\[18\\].bidir_pad",     #  7  PA18  HB_DQ5  / DBG_D5
    "bidirs\\[19\\].bidir_pad",     #  8  PA19  HB_DQ6  / DBG_D6
    "bidirs\\[20\\].bidir_pad",     #  9  PA20  HB_DQ7  / DBG_D7
    "bidirs\\[21\\].bidir_pad",     # 10  PA21  HB_RWDS / DBG_SEL0
    "bidirs\\[22\\].bidir_pad",     # 11  PA22  HB_CK   / DBG_SEL1
    "iovss_pads\\[0\\].iovss_pad"   # 12  IOVSS
]

PAD_EAST: [
    "bidirs\\[23\\].bidir_pad",     # 13  PA23  HB_CS0_N / DBG_SEL2
    "bidirs\\[24\\].bidir_pad",     # 14  PA24  HB_RST_N / DBG_SEL3
    "vss_pads\\[0\\].vss_pad",      # 15  VSS
    "outputs\\[0\\].output_pad",    # 16  CLK_OUT
    "vdd_pads\\[0\\].vdd_pad",      # 17  VDD
    "bidirs\\[0\\].bidir_pad",      # 18  PA0
    "bidirs\\[1\\].bidir_pad",      # 19  PA1  (irq)
    "bidirs\\[2\\].bidir_pad",      # 20  PA2  (irq)
    "iovss_pads\\[1\\].iovss_pad",  # 21  IOVSS
    "iovdd_pads\\[1\\].iovdd_pad",  # 22  IOVDD
    "bidirs\\[3\\].bidir_pad",      # 23  PA3  (irq)
    "bidirs\\[4\\].bidir_pad"       # 24  PA4  (irq)
]

PAD_NORTH: [
    "bidirs\\[12\\].bidir_pad",     # 36  PA12  QSPI0_CS2
    "bidirs\\[11\\].bidir_pad",     # 35  PA11  QSPI0_CS1
    "bidirs\\[10\\].bidir_pad",     # 34  PA10  QSPI0_CS0
    "vdd_pads\\[1\\].vdd_pad",      # 33  VDD
    "vss_pads\\[1\\].vss_pad",      # 32  VSS
    "bidirs\\[9\\].bidir_pad",      # 31  PA9   QSPI0_SCK
    "iovdd_pads\\[2\\].iovdd_pad",  # 30  IOVDD
    "iovss_pads\\[2\\].iovss_pad",  # 29  IOVSS
    "bidirs\\[8\\].bidir_pad",      # 28  PA8   QSPI0_IO3 (strap)
    "bidirs\\[7\\].bidir_pad",      # 27  PA7   QSPI0_IO2 (strap)
    "bidirs\\[6\\].bidir_pad",      # 26  PA6   QSPI0_IO1
    "bidirs\\[5\\].bidir_pad"       # 25  PA5   QSPI0_IO0
]

PAD_WEST: [
    "iovdd_pads\\[3\\].iovdd_pad",  # 48  IOVDD
    clk_pad,                        # 47  CLK
    "iovss_pads\\[3\\].iovss_pad",  # 46  IOVSS
    rst_n_pad,                      # 45  RST_N
    "inputs\\[3\\].input_pad",      # 44  UART0_RX
    "outputs\\[2\\].output_pad",    # 43  UART0_TX
    "vdd_pads\\[2\\].vdd_pad",      # 42  VDD
    "vss_pads\\[2\\].vss_pad",      # 41  VSS
    "outputs\\[1\\].output_pad",    # 40  TDO
    "inputs\\[2\\].input_pad",      # 39  TDI
    "inputs\\[1\\].input_pad",      # 38  TMS
    "inputs\\[0\\].input_pad"       # 37  TCK
]

# SDC files
PNR_SDC_FILE: dir::friscv_soc_top.sdc
SIGNOFF_SDC_FILE: dir::friscv_soc_top.sdc
FALLBACK_SDC: dir::friscv_soc_top.sdc

# Power / ground nets
VDD_NETS:
- VDD
GND_NETS:
- VSS

# Clock
CLOCK_PORT: clk_PAD
CLOCK_NET: clk_pad/p2c

CLOCK_PERIOD: 20

# Floorplanning
FP_SIZING: absolute
DIE_AREA: [0, 0, 2100, 2100]
CORE_AREA: [365, 365, 1735, 1735]

PL_TARGET_DENSITY_PCT: 85
GRT_ALLOW_CONGESTION: false

SETUP_VIOLATION_CORNERS: ["*"]

GRT_DESIGN_REPAIR_MAX_CAP_PCT: 30
GRT_DESIGN_REPAIR_MAX_SLEW_PCT: 30

MAX_CAP_VIOLATION_CORNERS: ["*"]

RUN_POST_GRT_DESIGN_REPAIR: true
RUN_POST_GRT_RESIZER_TIMING: true

CTS_APPLY_NDR: none

# PDN
PDN_CORE_RING: True

# Override bondpad name
PAD_BONDPAD_NAME: bondpad_70x70_5L

# Bondpad is not yet included in the PDK
EXTRA_GDS:
- dir::../ip/bondpad_70x70/gds/bondpad_70x70_5L.gds

EXTRA_LEFS:
- dir::../ip/bondpad_70x70/lef/bondpad_70x70_5L.lef

IGNORE_DISCONNECTED_MODULES:
- bondpad_70x70_5L

# Maximum metal width without slotting: 30um
PDN_CORE_RING_VWIDTH: 15
PDN_CORE_RING_HWIDTH: 15
# Ensure minimum spacing for long metals
PDN_CORE_RING_VSPACING: 5
PDN_CORE_RING_HSPACING: 5

PDN_CORE_RING_CONNECT_TO_PADS: true
PDN_ENABLE_PINS: false

# Because we have multiple power pads for one power domain
MAGIC_EXT_UNIQUE: notopports

MACROS:
  RM_IHPSG13_1P_1024x32_c2_bm_bist:
    gds:
      - pdk_dir::libs.ref/sg13cmos5l_sram/gds/RM_IHPSG13_1P_1024x32_c2_bm_bist.gds
    lef:
      - pdk_dir::libs.ref/sg13cmos5l_sram/lef/RM_IHPSG13_1P_1024x32_c2_bm_bist.lef
    vh:
      - pdk_dir::libs.ref/sg13cmos5l_sram/verilog/RM_IHPSG13_1P_1024x32_c2_bm_bist.v
      - pdk_dir::libs.ref/sg13cmos5l_sram/verilog/RM_IHPSG13_1P_core_behavioral_bm_bist.v
    lib:
      "*_typ_1p20V_25C":
        - pdk_dir::libs.ref/sg13cmos5l_sram/lib/RM_IHPSG13_1P_1024x32_c2_bm_bist_typ_1p20V_25C.lib
      "*_fast_1p32V_m40C":
        - pdk_dir::libs.ref/sg13cmos5l_sram/lib/RM_IHPSG13_1P_1024x32_c2_bm_bist_fast_1p32V_m55C.lib
      "*_slow_1p08V_125C":
        - pdk_dir::libs.ref/sg13cmos5l_sram/lib/RM_IHPSG13_1P_1024x32_c2_bm_bist_slow_1p08V_125C.lib
    instances:
      friscv_soc_inst.friscv_mem_hub.ocm_llc.gen_ways[0].way_sram.gen_1024x32.gen_cuts[0].i_cut:
        location: [613, 375]
        orientation: FS
      friscv_soc_inst.friscv_mem_hub.ocm_llc.gen_ways[1].way_sram.gen_1024x32.gen_cuts[0].i_cut:
        location: [1070, 375]
        orientation: FS
      friscv_soc_inst.friscv_mem_hub.ocm_llc.gen_ways[2].way_sram.gen_1024x32.gen_cuts[0].i_cut:
        location: [613, 1388]
        orientation: N
      friscv_soc_inst.friscv_mem_hub.ocm_llc.gen_ways[3].way_sram.gen_1024x32.gen_cuts[0].i_cut:
        location: [1070, 1388]
        orientation: N

  # Only instantiated when the LLC is built with SRAM_TAGS
  RM_IHPSG13_1P_64x64_c2_bm_bist:
    gds:
      - pdk_dir::libs.ref/sg13cmos5l_sram/gds/RM_IHPSG13_1P_64x64_c2_bm_bist.gds
    lef:
      - pdk_dir::libs.ref/sg13cmos5l_sram/lef/RM_IHPSG13_1P_64x64_c2_bm_bist.lef
    vh:
      - pdk_dir::libs.ref/sg13cmos5l_sram/verilog/RM_IHPSG13_1P_64x64_c2_bm_bist.v
      - pdk_dir::libs.ref/sg13cmos5l_sram/verilog/RM_IHPSG13_1P_core_behavioral_bm_bist.v
    lib:
      "*_typ_1p20V_25C":
        - pdk_dir::libs.ref/sg13cmos5l_sram/lib/RM_IHPSG13_1P_64x64_c2_bm_bist_typ_1p20V_25C.lib
      "*_fast_1p32V_m40C":
        - pdk_dir::libs.ref/sg13cmos5l_sram/lib/RM_IHPSG13_1P_64x64_c2_bm_bist_fast_1p32V_m55C.lib
      "*_slow_1p08V_125C":
        - pdk_dir::libs.ref/sg13cmos5l_sram/lib/RM_IHPSG13_1P_64x64_c2_bm_bist_slow_1p08V_125C.lib
    instances:
      friscv_soc_inst.friscv_mem_hub.ocm_llc.gen_tag_sram.tag_sram.gen_64x64.i_cut:
        location: [613, 800]
        orientation: N

# This is an alternative method compared to
# specifying the power connections in the RTL
PDN_MACRO_CONNECTIONS:
- ".*gen_1024x32.gen_cuts.*i_cut VDD VSS VDDARRAY! VSS!"
- ".*gen_1024x32.gen_cuts.*i_cut VDD VSS VDD! VSS!"
- ".*gen_64x64.i_cut VDD VSS VDDARRAY! VSS!"
- ".*gen_64x64.i_cut VDD VSS VDD! VSS!"
